### ISSUE TITLE
Missing include dir for TRE library

### ISSUE THREAD

**Issue by danielt3** [isage/sorr-vita#11]
The build system can't find the TRE library include dir when a clean checkout is done. The `TRE_INCLUDE_DIR` var in the `CMakeLists.txt` file is empty. Likely you preset some variable to make it work.

I was able to make it work by manully adding `${CMAKE_SOURCE_DIR}/3rdparty/tre/lib` to the `target_include_directories` of BGDRTM but I don't think this is the proper way to fix this. I don't know CMake enough to implement a better solution but I can send a PR if you want.

Another suggestion is to make CMake fail when TRE include is not found.

**Comment by isage** [comment]
Yeah, that's the proper way. I had TRE installed, before migrating to building it in-project, that's why it worked for me.

**Comment by danielt3** [comment]
Fixed in #13. Please, review.
